### ISSUE TITLE
translucent render

### ISSUE THREAD

**Issue by 980538137** [Antoshidza/NSprites-Foundation#11]
When I use SpriteRendererAuthoriing and there is a translucent part in the texture, the translucent part cannot be displayed. How can I solve this problem?

**Comment by Antoshidza** [comment]
Hi! I guess you would need to rewrite shader a bit, because whole project aiming pure performance and translucent is evil in terms  of performance.

It is probably [this line in shader](https://github.com/Antoshidza/NSprites-Foundation/blob/abbdd073ddc9d91f309f4efe123713aecd8becee/Graphics/Regular%20Render/RegularNSprites_Shader.shader#L147C16-L147C40)
