### ISSUE TITLE
Rotation Support

### ISSUE THREAD

**Issue by JeroenoBoy** [Antoshidza/NSprites-Foundation#2]
For the game I am making, I need sprites to be able to rotate.

Could this feature be added to the library?

**Comment by Antoshidza** [comment]
Yes, it can be implemented, but it should be a part of `Transform2D` and have all stuff like parent -> child rotation computations OR foundation should refuse to use 2D and instead use all 3D `Unity.Transform` components and instead of constructing matrix in shader just pass it in. So I need to think what is a better way.

If you want it right here and now, then you can implement it by yourself.
There are 3 possible ways I can imagine of how it can be done. (as a shader reference I will use https://github.com/Antoshidza/NSprites-Foundation/blob/main/Graphics/Regular%20Render/RegularNSprites_Shader.shader)

* Sending rotation `float4` struct to `StructuredBuffer<float4>` in your shader and then in `setup` function apply this structure as a rotation (`quaternion`) in `float4x4` matrix construction. Though I'm not sure of how to apply rotation to matrix (seems we can use [this](https://github.com/Unity-Technologies/UnityCsReference/blob/master/Runtime/Export/Math/Matrix4x4.cs#L370) as an example)
* Using unity built-in `Unity.Transform` systems to have `float4x4` matrix and pass this value to shader (in this way all we need is to just stop using `Transform2D` from this foundation and use built-in solution + register it's matrix component as instanced, if I'm not mistaken it called something like `LocalToWorld`)
* Constructing 2D matrix as it goes in built-in `Unity.Transforms` matrix but only for 2D needs. It can be smaller matrix or just leave unused 4x4 matrix components in default values. Then as previous way says - pass it in shader as `StructuredBuffer<float4x4>`.

**Comment by Antoshidza** [comment]
After a bit thinking I've decide that

* If you want to use 2D it is better to implement 2D rotation to avoid passing and allocate unnecessary data + still possible to do this
* If you want to use 3D then it is better to stick with unity's `Unity.Transforms` and register theirs components as instanced components for NSprites.

What type of game you developing? 2D / 2,5D / 3D ?

**Comment by JeroenoBoy** [comment]
Hi, the game I'm currently making is 2d. If you want an idea of what I'm trying to make, think reassembly, but way bigger.

**Comment by JeroenoBoy** [comment]
After some fiddeling around, I've got it to work on my fork https://github.com/JeroenoBoy/Fundering

**Comment by Antoshidza** [comment]
That's good. I've been on vacation, so now can return to work. I need to complete authoring refactoring, and then merge your changes, because I see that you also find and fix those bugs.

**Comment by Antoshidza** [comment]
From now this package allows rotations ([merged](https://github.com/Antoshidza/NSprites-Foundation/pull/3)). Thanks for @JeroenoBoy
