### ISSUE TITLE
Ability to choose number of frames in an animation

### ISSUE THREAD

**Issue by meditatingsloth** [Antoshidza/NSprites-Foundation#8]
I have a sprite sheet that isn't completely filled out (5 slices on a 3x2 grid), however I noticed the animation system expects to use all slices of a grid. On the surface it seems trivial to limit the number of frames the system tries to run through, this is what I tried:

- Removed the `OnValidate()` method in SpriteAnimation
- Set my frame durations in my animation to 5
- Changed [this line](https://github.com/Antoshidza/NSprites-Foundation/blob/bab3bdec642c1cd12b2d64eb1a450a4e70421507/Animation/Systems/SpriteUVAnimationSystem.cs#L31) to use animData.FrameDurations.Length

However, I noticed an empty frame still renders. Any idea what I might be missing?

**Comment by Antoshidza** [comment]
If your `frameCount` is limited to durations array length then `frameIndex` should also looped between `0` and `frameCount - 1` inclusive, which means empty frame shouldn't be rendered.

Have you debug actual `frameCount` in `SpriteUVAnimationSystem.cs` ?

**Comment by meditatingsloth** [comment]
Yes, everything looks fine in the debugger with `frameIndex.value` (loops 0-4 as expected) and `framePosition` looks to be set correctly on each loop as well (never reads the 2,1 position as expected).

**Comment by Antoshidza** [comment]
Looks weird, I'll try the same as soon as I can to find a problem

**Comment by Antoshidza** [comment]
I do the same. change line, remove validate and change animation asset and all works. I actually have no idea yet because as you mentioned you see proper values in debug but still wrong result in scene.

Can you show your texture sheet? And also do you use shader from foundation or implement your own?

Also try to save project before enter playmode, because it could be something wrong with how unity react to animation asset changes. Though for me all works with opened subscene.

**Comment by meditatingsloth** [comment]
That is strange indeed. Thanks for checking. I'm going to try it again in a fresh project, maybe the old package is cached or something as I originally had this repo installed before updating to my fork. I've attached the sprite I'm using to test as well in case that makes a difference.

Also yes, I'm using the default "Regular" material/shader from NSprites

![ship1](https://github.com/Antoshidza/NSprites-Foundation/assets/3280166/87e4c9d9-715f-4e0f-9ba9-6617d447e8ab)

**Comment by meditatingsloth** [comment]
I'm able to replicate the flickering in a fresh project: https://github.com/meditatingsloth/Sandbox

A couple notes:

- I had to update the Renderer2D URP asset to a normal Renderer URP (the one that's created with the 2D URP template does not work with NSprites it looks like)
- I'm using the latest version of the Entities package.
- I've used NSprites animation with a fully filled out sprite sheet and there's no flicker so it seems to be coming from the animation system

**Comment by Antoshidza** [comment]
> I had to update the Renderer2D URP asset to a normal Renderer URP (the one that's created with the 2D URP template does not work with NSprites it looks like)

Yes, for Renderer2D URP you should implement compatible shader.

Will try it with your project.

**Comment by Antoshidza** [comment]
I've found out that all this time UV calculations was wrong, because 0.0 it seems starts from left bottom point instead left up point. So index `2` of our 5 frames pointing to last frame in texture sheet (which have 5 index). I've fixed it in this [commit](https://github.com/Antoshidza/NSprites-Foundation/commit/d83d95d09a71904a04e84383d18ea13ed513811a).

**Comment by meditatingsloth** [comment]
> I've found out that all this time UV calculations was wrong, because 0.0 it seems starts from left bottom point instead left up point. So index `2` of our 5 frames pointing to last frame in texture sheet (which have 5 index). I've fixed it in this [commit](https://github.com/Antoshidza/NSprites-Foundation/commit/d83d95d09a71904a04e84383d18ea13ed513811a).

Ahh I didn't even think of that, thank you for looking into it!
